/*
 * Calc
 *
 * Simple calculator API hosted on APIMATIC
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Is thrown when invalid input is given such as div by zero
type CouldNotCompute struct {
	// Represents the server's exception message
	ServerMessage string `json:"ServerMessage"`
	// Represents the server's error code
	ServerCode int32 `json:"ServerCode"`
}
