/*
 * Calc
 *
 * Simple calculator API hosted on APIMATIC
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// OperationType : Possible operators are sum, subtract, multiply, divide
type OperationType string

// List of OperationType
const (
	SUM_OperationType OperationType = "SUM"
	SUBTRACT_OperationType OperationType = "SUBTRACT"
	MULTIPLY_OperationType OperationType = "MULTIPLY"
	DIVIDE_OperationType OperationType = "DIVIDE"
)
